<form action="/users/<?= htmlspecialchars($user['id']) ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
      <label>
          Название *
          <input type="text" name="user[name]" value="<?= htmlspecialchars($user['name'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['name'])): ?>
          <div><?= $errors['name'] ?></div>
      <?php endif ?>
    </div>
    <div>
      <label>
          Пол *
          <input type="text" name="user[sex]" value="<?= htmlspecialchars($user['sex'] ?? ''); ?>">
      </label>
      <?php if (isset($errors['sex'])): ?>
          <div><?= $errors['sex'] ?></div>
      <?php endif ?>
    </div>

    <input type="submit" value="Update">
</form>

