<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>


<a href="/users/new">Новый пользователь</a>

<?php foreach ($users as $user): ?>
 <div> 
       <a href="/users/<?= $user['name'] ?>"><?= htmlspecialchars($user['name']) ?></a>
 </div>
 <div>
	<?= htmlspecialchars($user['sex']) ?>
 </div>
<?php endforeach ?>

