<a href="/users/new">Новый пользователь</a>

<?php foreach ($users as $user): ?>
  <div>
     <?= htmlspecialchars($user['title']) ?>
  </div>
<?php endforeach ?>


<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>
